name = "CardanoProphet/veriscript-contracts"
version = "0.1.0"
compiler = "v1.1.21"
plutus = "v3"
license = "MIT"
description = "Aiken contracts for project 'VeriScript'"

[repository]
user = "CardanoProphet"
project = "veriscript-contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.1.1"
source = "github"

# TODO: fill in anchor_ix and anchor_tx_id at deployment.

[config.default]
network = "mainnet"
anchor_ix = 0
[config.default.anchor_tx_id]
bytes = "abcdef"
encoding = "hex"
[config.default.protocol_parameters_script_hash]
bytes = "11c5063f334dc70aa10d19f453e324ceca2e738dff6736f3d2fb57ee"
encoding = "hex"

[config.preprod]
network = "preprod"
anchor_ix = 6
[config.preprod.anchor_tx_id]
bytes = "2032d4c8b92f18ebd00dee97246dea52128bc8a72e390ff8ce51c1e0ec345b6a"
encoding = "hex"
[config.preprod.protocol_parameters_script_hash]
bytes = "ad256fd9053143b5f0370099ab59bc5dc356623faa4a7ac2c1956883"
encoding = "hex"
